"""
Scan repo for literal-string DB password bug patterns.

This catches mistakes where code contains the text of the env lookup
instead of executing the lookup expression.
"""
from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
REPORT = ROOT / "docs" / "PARALLEL_PHASE1_PASSWORD_AUDIT.md"

SKIP_DIRS = {
    ".git",
    ".pytest_cache",
    "__pycache__",
    ".claude",
    "archive",
    "logs",
    "output",
    "reports",
    "password_fix_backups",
}
EXTENSIONS = {".py"}

BROKEN_PATTERNS = [
    '"os.environ.get(\'DB_PASSWORD\', \'\')"',
    '"os.environ.get("DB_PASSWORD", "")"',
    "'os.environ.get('DB_PASSWORD', '')'",
    '\'os.environ.get("DB_PASSWORD", "")\'',
]


def should_scan(path: Path) -> bool:
    rel_parts = path.relative_to(ROOT).parts
    if rel_parts[:2] == ("scripts", "analysis"):
        return False
    if any(part in SKIP_DIRS for part in path.parts):
        return False
    if path.suffix.lower() not in EXTENSIONS:
        return False
    return True


def main() -> int:
    findings: list[str] = []
    for path in ROOT.rglob("*"):
        if not path.is_file() or not should_scan(path):
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except Exception:
            continue

        for idx, line in enumerate(text.splitlines(), start=1):
            for pattern in BROKEN_PATTERNS:
                if pattern in line:
                    rel = path.relative_to(ROOT)
                    findings.append(f"{rel}:{idx}: {line.strip()}")

    lines = [
        "# Parallel Phase 1 Password Audit",
        "",
        "Generated by `scripts/analysis/find_literal_password_bug.py`.",
        "",
        f"- Findings: {len(findings)}",
        "",
        "## Matches",
    ]

    if findings:
        lines.extend([f"- `{f}`" for f in findings])
    else:
        lines.append("- None")

    REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote: {REPORT}")
    print(f"Findings: {len(findings)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
