"""
Generate a database inventory report for PROJECT_STATE.md.

Usage:
    py scripts/maintenance/generate_db_inventory.py
    py scripts/maintenance/generate_db_inventory.py --markdown  # output as markdown

Outputs table counts, row counts, view counts, MV counts, and database size.
"""
import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..'))

from db_config import get_connection
from datetime import datetime


def generate_inventory(markdown=False):
    conn = get_connection()
    cur = conn.cursor()

    # Database size
    cur.execute("SELECT pg_size_pretty(pg_database_size(current_database()))")
    db_size = cur.fetchone()[0]

    # Table count and row estimates (pg_stat_user_tables is fast)
    cur.execute("""
        SELECT schemaname, relname, n_live_tup
        FROM pg_stat_user_tables
        WHERE schemaname = 'public'
        ORDER BY n_live_tup DESC
    """)
    tables = cur.fetchall()

    # View count
    cur.execute("""
        SELECT count(*) FROM information_schema.views
        WHERE table_schema = 'public'
    """)
    view_count = cur.fetchone()[0]

    # Materialized views with row counts
    cur.execute("""
        SELECT c.relname, c.reltuples::bigint
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relkind = 'm' AND n.nspname = 'public'
        ORDER BY c.reltuples DESC
    """)
    mvs = cur.fetchall()

    # Index count and size
    cur.execute("""
        SELECT count(*),
               pg_size_pretty(sum(pg_relation_size(indexrelid)))
        FROM pg_stat_user_indexes
        WHERE schemaname = 'public'
    """)
    idx_count, idx_size = cur.fetchone()

    cur.close()
    conn.close()

    total_rows = sum(r[2] for r in tables)
    table_count = len(tables)
    now = datetime.now().strftime('%Y-%m-%d %H:%M')

    if markdown:
        lines = []
        lines.append(f"*Auto-generated by `scripts/maintenance/generate_db_inventory.py` on {now}. Re-run to refresh.*\n")
        lines.append(f"| Metric | Value |")
        lines.append(f"|--------|-------|")
        lines.append(f"| Database size | {db_size} |")
        lines.append(f"| Tables | {table_count} |")
        lines.append(f"| Views | {view_count} |")
        lines.append(f"| Materialized views | {len(mvs)} |")
        lines.append(f"| Indexes | {idx_count} (total size: {idx_size}) |")
        lines.append(f"| Estimated total rows | {total_rows:,} |")
        lines.append("")

        # Materialized views detail
        lines.append("**Materialized Views:**\n")
        lines.append("| View | Rows |")
        lines.append("|------|------|")
        for name, rows in mvs:
            lines.append(f"| `{name}` | {rows:,} |")
        lines.append("")

        # Top 30 tables by row count
        lines.append("**Top 30 Tables by Row Count:**\n")
        lines.append("| Table | Rows |")
        lines.append("|-------|------|")
        for schema, name, rows in tables[:30]:
            lines.append(f"| `{name}` | {rows:,} |")
        lines.append("")

        # All tables summary (collapsed)
        lines.append(f"*{table_count} tables total. {sum(1 for _, _, r in tables if r == 0)} empty tables.*")

        print("\n".join(lines))
    else:
        print(f"Database Inventory — {now}")
        print(f"{'='*50}")
        print(f"  Database size:       {db_size}")
        print(f"  Tables:              {table_count}")
        print(f"  Views:               {view_count}")
        print(f"  Materialized views:  {len(mvs)}")
        print(f"  Indexes:             {idx_count} (total size: {idx_size})")
        print(f"  Estimated rows:      {total_rows:,}")
        print()

        print("Materialized Views:")
        for name, rows in mvs:
            print(f"  {name}: {rows:,}")
        print()

        print("Top 30 Tables by Row Count:")
        for schema, name, rows in tables[:30]:
            print(f"  {name}: {rows:,}")
        print()
        print(f"{table_count} tables total. {sum(1 for _, _, r in tables if r == 0)} empty.")


if __name__ == '__main__':
    md = '--markdown' in sys.argv
    generate_inventory(markdown=md)
