"""Canonical data source inventory for the Labor Relations Research Platform."""

DATA_SOURCE_INVENTORY_LAST_UPDATED = "2026-03-04"

DATA_SOURCE_GROUPS = [
    {
        "group_id": "core_union_reference",
        "title": "Core Union Reference Data",
        "order": 1,
    },
    {
        "group_id": "enforcement_workplace_conditions",
        "title": "Enforcement & Workplace Conditions",
        "order": 2,
    },
    {
        "group_id": "bls_labor_statistics",
        "title": "BLS Labor Statistics",
        "order": 3,
    },
    {
        "group_id": "corporate_identity_hierarchy",
        "title": "Corporate Identity & Hierarchy",
        "order": 4,
    },
    {
        "group_id": "federal_contracting_tax",
        "title": "Federal Contracting & Tax Data",
        "order": 5,
    },
    {
        "group_id": "census_demographics",
        "title": "Census & Demographics",
        "order": 6,
    },
    {
        "group_id": "master_matching",
        "title": "Master Employer & Matching Infrastructure",
        "order": 7,
    },
    {
        "group_id": "scoring_pipeline",
        "title": "Scoring Pipeline",
        "order": 8,
    },
    {
        "group_id": "research_cba",
        "title": "Research & CBA",
        "order": 9,
    },
    {
        "group_id": "specialized_regional",
        "title": "Specialized / Regional",
        "order": 10,
    },
]

# Notes:
# - count_query/date_query are used by scripts/maintenance/create_data_freshness.py.
# - Multi-table sources use aggregate counts (sum across tables) where practical.
DATA_SOURCE_ENTRIES = [
    {
        "source_name": "f7_union_filings",
        "display_name": "F-7 Union Filings",
        "group_id": "core_union_reference",
        "tables": ["unions_master", "f7_employers_deduped", "f7_union_employer_relations"],
        "record_count_note": "~146,863 employers (67,500 current + 79,000 historical)",
        "description": "Comprehensive registry of union-employer bargaining relationships.",
        "count_query": "SELECT COUNT(*) FROM f7_employers_deduped",
        "date_query": None,
        "freshness_notes": "FMCS / DOL F-7 employer-union relationships",
    },
    {
        "source_name": "nlrb_elections_cases",
        "display_name": "NLRB Elections and Cases",
        "group_id": "core_union_reference",
        "tables": ["nlrb_elections", "nlrb_participants", "nlrb_cases", "nlrb_allegations", "nlrb_docket", "nlrb_filings", "nlrb_tallies"],
        "record_count_note": "~33,000 elections, ~478,000 cases, ~1.9M participants, ~716,000 allegations, ~2M docket entries",
        "description": "Election outcomes, ULP activity, participants, and procedural history.",
        "count_query": "SELECT (SELECT COUNT(*) FROM nlrb_elections) + (SELECT COUNT(*) FROM nlrb_cases) + (SELECT COUNT(*) FROM nlrb_participants) + (SELECT COUNT(*) FROM nlrb_allegations) + (SELECT COUNT(*) FROM nlrb_docket)",
        "date_query": "SELECT MIN(d), MAX(d) FROM (SELECT MIN(election_date) AS d, MAX(election_date) AS x FROM nlrb_elections UNION ALL SELECT MIN(earliest_date), MAX(latest_date) FROM nlrb_cases) q",
        "freshness_notes": "NLRB elections, cases, and allegations",
    },
    {
        "source_name": "lm_filings",
        "display_name": "LM Union Financial Filings",
        "group_id": "core_union_reference",
        "tables": ["lm_data"],
        "record_count_note": "~331,000 rows (2010-2024)",
        "description": "Union financial reports from LM-2/3/4 filings.",
        "count_query": "SELECT COUNT(*) FROM lm_data",
        "date_query": "SELECT MIN(fiscal_year_start), MAX(fiscal_year_end) FROM lm_data",
        "freshness_notes": "OLMS LM filings",
    },
    {
        "source_name": "osha_workplace_safety",
        "display_name": "OSHA Workplace Safety",
        "group_id": "enforcement_workplace_conditions",
        "tables": ["osha_establishments", "osha_violations_detail", "osha_violation_summary"],
        "record_count_note": "~1M workplaces, ~2.2M violations",
        "description": "Safety inspections and violation details at establishment level.",
        "count_query": "SELECT (SELECT COUNT(*) FROM osha_establishments) + (SELECT COUNT(*) FROM osha_violations_detail)",
        "date_query": "SELECT MIN(issuance_date), MAX(issuance_date) FROM osha_violations_detail",
        "freshness_notes": "OSHA establishments and violations",
    },
    {
        "source_name": "whd_wage_hour",
        "display_name": "WHD Wage and Hour",
        "group_id": "enforcement_workplace_conditions",
        "tables": ["whd_cases", "mv_whd_employer_agg"],
        "record_count_note": "~363,000 cases (2005-2025)",
        "description": "Wage theft and labor standards enforcement outcomes.",
        "count_query": "SELECT COUNT(*) FROM whd_cases",
        "date_query": "SELECT MIN(findings_start_date), MAX(findings_end_date) FROM whd_cases WHERE findings_end_date < '2100-01-01'",
        "freshness_notes": "DOL Wage and Hour enforcement",
    },
    {
        "source_name": "oes_wages",
        "display_name": "OES Occupational Wages",
        "group_id": "bls_labor_statistics",
        "tables": ["oes_occupation_wages", "mv_oes_area_wages"],
        "record_count_note": "~414,000 wage rows",
        "description": "Occupation x area x industry wage benchmarks.",
        "count_query": "SELECT COUNT(*) FROM oes_occupation_wages",
        "date_query": None,
        "freshness_notes": "BLS OES occupation wage benchmarks",
    },
    {
        "source_name": "soii_injury_rates",
        "display_name": "SOII Injury Rates",
        "group_id": "bls_labor_statistics",
        "tables": ["bls_soii_series", "bls_soii_data", "mv_soii_industry_rates"],
        "record_count_note": "~891,000 series + ~5.7M points",
        "description": "Industry injury and illness rates over time.",
        "count_query": "SELECT (SELECT COUNT(*) FROM bls_soii_series) + (SELECT COUNT(*) FROM bls_soii_data)",
        "date_query": "SELECT make_date(MIN(year), 1, 1), make_date(MAX(year), 12, 31) FROM bls_soii_data",
        "freshness_notes": "BLS SOII industry injury rates",
    },
    {
        "source_name": "jolts_turnover",
        "display_name": "JOLTS Turnover",
        "group_id": "bls_labor_statistics",
        "tables": ["bls_jolts_series", "bls_jolts_data", "mv_jolts_industry_rates"],
        "record_count_note": "~2,000 series + ~370,000 data points",
        "description": "Hires, quits, openings, and separations by industry.",
        "count_query": "SELECT (SELECT COUNT(*) FROM bls_jolts_series) + (SELECT COUNT(*) FROM bls_jolts_data)",
        "date_query": None,
        "freshness_notes": "BLS JOLTS labor turnover",
    },
    {
        "source_name": "ncs_benefits",
        "display_name": "NCS Benefits Access",
        "group_id": "bls_labor_statistics",
        "tables": ["bls_ncs_series", "bls_ncs_data", "mv_ncs_benefits_access"],
        "record_count_note": "~100,000 series + ~768,000 data points",
        "description": "Benefit access rates by industry and worker segment.",
        "count_query": "SELECT (SELECT COUNT(*) FROM bls_ncs_series) + (SELECT COUNT(*) FROM bls_ncs_data)",
        "date_query": None,
        "freshness_notes": "BLS NCS benefits access",
    },
    {
        "source_name": "qcew_county_wages",
        "display_name": "QCEW County Employment and Wages",
        "group_id": "bls_labor_statistics",
        "tables": ["qcew_annual"],
        "record_count_note": "~1.9M rows",
        "description": "County-level employment and average wage by industry.",
        "count_query": "SELECT COUNT(*) FROM qcew_annual",
        "date_query": "SELECT make_date(MIN(year), 1, 1), make_date(MAX(year), 12, 31) FROM qcew_annual",
        "freshness_notes": "BLS QCEW annual county statistics",
    },
    {
        "source_name": "union_density",
        "display_name": "Union Density Benchmarks",
        "group_id": "bls_labor_statistics",
        "tables": ["bls_industry_density", "bls_state_density", "state_sector_union_density", "bls_national_industry_density", "estimated_state_industry_density"],
        "record_count_note": "National + state + state-sector series (1978-2025)",
        "description": "Union membership density by state, industry, and sector.",
        "count_query": "SELECT (SELECT COUNT(*) FROM bls_industry_density) + (SELECT COUNT(*) FROM bls_state_density) + (SELECT COUNT(*) FROM state_sector_union_density) + (SELECT COUNT(*) FROM bls_national_industry_density) + (SELECT COUNT(*) FROM estimated_state_industry_density)",
        "date_query": "SELECT make_date(MIN(year), 1, 1), make_date(MAX(year), 12, 31) FROM bls_state_density",
        "freshness_notes": "BLS union density indicators",
    },
    {
        "source_name": "staffing_patterns",
        "display_name": "Industry Staffing Patterns",
        "group_id": "bls_labor_statistics",
        "tables": ["bls_industry_occupation_matrix", "occupation_similarity", "industry_occupation_overlap", "naics_to_bls_industry"],
        "record_count_note": "~67,000 mappings plus overlap/similarity scores",
        "description": "Occupation mix by industry and comparable-workforce signals.",
        "count_query": "SELECT (SELECT COUNT(*) FROM bls_industry_occupation_matrix) + (SELECT COUNT(*) FROM occupation_similarity) + (SELECT COUNT(*) FROM industry_occupation_overlap)",
        "date_query": None,
        "freshness_notes": "BLS staffing pattern and similarity matrices",
    },
    {
        "source_name": "sec_edgar",
        "display_name": "SEC EDGAR Companies",
        "group_id": "corporate_identity_hierarchy",
        "tables": ["sec_companies"],
        "record_count_note": "~517,000 companies",
        "description": "Public-company identifiers and filing-derived attributes.",
        "count_query": "SELECT COUNT(*) FROM sec_companies",
        "date_query": None,
        "freshness_notes": "SEC EDGAR company registry",
    },
    {
        "source_name": "gleif_ownership",
        "display_name": "GLEIF Ownership",
        "group_id": "corporate_identity_hierarchy",
        "tables": ["gleif_us_entities", "gleif_ownership_links"],
        "record_count_note": "~379,000 entities + ~499,000 ownership links",
        "description": "Legal-entity parent-child ownership chains.",
        "count_query": "SELECT (SELECT COUNT(*) FROM gleif_us_entities) + (SELECT COUNT(*) FROM gleif_ownership_links)",
        "date_query": None,
        "freshness_notes": "GLEIF entities and ownership links",
    },
    {
        "source_name": "corpwatch_genealogy",
        "display_name": "CorpWatch Corporate Genealogy",
        "group_id": "corporate_identity_hierarchy",
        "tables": ["corpwatch_companies", "corpwatch_relationships"],
        "record_count_note": "~1.4M companies + ~3.5M relationships",
        "description": "Historical and deep corporate parent-subsidiary structure.",
        "count_query": "SELECT (SELECT COUNT(*) FROM corpwatch_companies) + (SELECT COUNT(*) FROM corpwatch_relationships)",
        "date_query": None,
        "freshness_notes": "CorpWatch company and relationship graph",
    },
    {
        "source_name": "mergent_business_intel",
        "display_name": "Mergent or D&B Business Intelligence",
        "group_id": "corporate_identity_hierarchy",
        "tables": ["mergent_employers"],
        "record_count_note": "~56,000 enriched companies",
        "description": "Private-company enrichment including revenue and employee counts.",
        "count_query": "SELECT COUNT(*) FROM mergent_employers",
        "date_query": None,
        "freshness_notes": "Mergent enriched employer profiles",
    },
    {
        "source_name": "corporate_crosswalk",
        "display_name": "Corporate Identifier Crosswalk",
        "group_id": "corporate_identity_hierarchy",
        "tables": ["corporate_identifier_crosswalk", "corporate_hierarchy"],
        "record_count_note": "~17,111 crosswalk rows + ~125,000 hierarchy links",
        "description": "Bridges CIK, LEI, DUNS, and platform employer identifiers.",
        "count_query": "SELECT (SELECT COUNT(*) FROM corporate_identifier_crosswalk) + (SELECT COUNT(*) FROM corporate_hierarchy)",
        "date_query": None,
        "freshness_notes": "Cross-system corporate identifier linking",
    },
    {
        "source_name": "sam_federal_contractors",
        "display_name": "SAM.gov Federal Contractors",
        "group_id": "federal_contracting_tax",
        "tables": ["sam_entities"],
        "record_count_note": "~826,000 entities",
        "description": "Federal contractor registration and entity attributes.",
        "count_query": "SELECT COUNT(*) FROM sam_entities",
        "date_query": None,
        "freshness_notes": "SAM entity registry",
    },
    {
        "source_name": "usaspending_contract_dollars",
        "display_name": "USAspending Contract Dollars",
        "group_id": "federal_contracting_tax",
        "tables": ["cur_usaspending_recipient_rollup"],
        "record_count_note": "~94,000 recipients",
        "description": "Federal contract dollars by recipient and year.",
        "count_query": "SELECT COUNT(*) FROM cur_usaspending_recipient_rollup",
        "date_query": None,
        "freshness_notes": "Federal obligations by contractor recipient",
    },
    {
        "source_name": "form_990_nonprofits",
        "display_name": "Form 990 Nonprofit Financials",
        "group_id": "federal_contracting_tax",
        "tables": ["national_990_filers", "employers_990_deduped", "national_990_f7_matches"],
        "record_count_note": "~587,000 filers + ~1M deduped + ~20,000 F-7 matches",
        "description": "IRS nonprofit financial and leadership filings.",
        "count_query": "SELECT (SELECT COUNT(*) FROM national_990_filers) + (SELECT COUNT(*) FROM employers_990_deduped) + (SELECT COUNT(*) FROM national_990_f7_matches)",
        "date_query": None,
        "freshness_notes": "IRS Form 990 and match outputs",
    },
    {
        "source_name": "irs_business_master_file",
        "display_name": "IRS Business Master File",
        "group_id": "federal_contracting_tax",
        "tables": ["irs_bmf"],
        "record_count_note": "~300,000 tax-exempt organizations",
        "description": "Tax-exempt classification and ruling metadata.",
        "count_query": "SELECT COUNT(*) FROM irs_bmf",
        "date_query": None,
        "freshness_notes": "IRS BMF organization registry",
    },
    {
        "source_name": "form_5500_benefit_plans",
        "display_name": "Form 5500 Benefit Plans",
        "group_id": "federal_contracting_tax",
        "tables": ["cur_form5500_sponsor_rollup"],
        "record_count_note": "~259,000 sponsors",
        "description": "Employer retirement and health plan sponsor rollups.",
        "count_query": "SELECT COUNT(*) FROM cur_form5500_sponsor_rollup",
        "date_query": None,
        "freshness_notes": "Form 5500 sponsor-level rollups",
    },
    {
        "source_name": "ppp_loans",
        "display_name": "PPP Loan Data",
        "group_id": "federal_contracting_tax",
        "tables": ["cur_ppp_employer_rollup"],
        "record_count_note": "~9.5M borrowers",
        "description": "PPP loan and forgiveness records with reported jobs.",
        "count_query": "SELECT COUNT(*) FROM cur_ppp_employer_rollup",
        "date_query": None,
        "freshness_notes": "PPP employer rollup",
    },
    {
        "source_name": "acs_workforce_demographics",
        "display_name": "ACS Workforce Demographics",
        "group_id": "census_demographics",
        "tables": ["newsrc_acs_occ_demo_profiles", "cur_acs_workforce_demographics"],
        "record_count_note": "~11.5M rows",
        "description": "Demographic workforce composition by geo x industry x occupation.",
        "count_query": "SELECT (SELECT COUNT(*) FROM newsrc_acs_occ_demo_profiles) + (SELECT COUNT(*) FROM cur_acs_workforce_demographics)",
        "date_query": None,
        "freshness_notes": "ACS workforce demographic profiles",
    },
    {
        "source_name": "cbp_county_business_patterns",
        "display_name": "County Business Patterns",
        "group_id": "census_demographics",
        "tables": ["cur_cbp_geo_naics"],
        "record_count_note": "~1.5M rows",
        "description": "County x industry establishment and employment counts.",
        "count_query": "SELECT COUNT(*) FROM cur_cbp_geo_naics",
        "date_query": None,
        "freshness_notes": "Census County Business Patterns",
    },
    {
        "source_name": "lodes_commuting_patterns",
        "display_name": "LODES Commuting Patterns",
        "group_id": "census_demographics",
        "tables": ["cur_lodes_geo_metrics"],
        "record_count_note": "~3,000 county metrics",
        "description": "Workplace-residence commuting and earnings distributions.",
        "count_query": "SELECT COUNT(*) FROM cur_lodes_geo_metrics",
        "date_query": None,
        "freshness_notes": "Census LODES county metrics",
    },
    {
        "source_name": "abs_business_survey",
        "display_name": "Annual Business Survey",
        "group_id": "census_demographics",
        "tables": ["cur_abs_geo_naics"],
        "record_count_note": "~112,000 rows",
        "description": "Ownership diversity indicators by state and industry.",
        "count_query": "SELECT COUNT(*) FROM cur_abs_geo_naics",
        "date_query": None,
        "freshness_notes": "Census ABS firm demographics",
    },
    {
        "source_name": "census_rpe_ratios",
        "display_name": "Census Revenue-per-Employee Ratios",
        "group_id": "census_demographics",
        "tables": ["census_rpe_ratios"],
        "record_count_note": "Ratios by industry and geography",
        "description": "Economic Census revenue-to-employment benchmark ratios.",
        "count_query": "SELECT COUNT(*) FROM census_rpe_ratios",
        "date_query": None,
        "freshness_notes": "Economic Census revenue-per-employee ratios",
    },
    {
        "source_name": "master_employers",
        "display_name": "Master Employers Registry",
        "group_id": "master_matching",
        "tables": ["master_employers", "master_employer_source_ids"],
        "record_count_note": "~4.4M unified employers",
        "description": "Canonical employer identities across all source systems.",
        "count_query": "SELECT COUNT(*) FROM master_employers",
        "date_query": "SELECT MIN(created_at), MAX(updated_at) FROM master_employers",
        "freshness_notes": "Unified master employer registry",
    },
    {
        "source_name": "match_tables",
        "display_name": "Match Tables",
        "group_id": "master_matching",
        "tables": ["osha_f7_matches", "whd_f7_matches", "sam_f7_matches", "nlrb_employer_xref", "unified_match_log"],
        "record_count_note": "~2.2M match audit entries",
        "description": "Cross-source linking and confidence-scored audit trails.",
        "count_query": "SELECT (SELECT COUNT(*) FROM osha_f7_matches) + (SELECT COUNT(*) FROM whd_f7_matches) + (SELECT COUNT(*) FROM sam_f7_matches) + (SELECT COUNT(*) FROM nlrb_employer_xref) + (SELECT COUNT(*) FROM unified_match_log)",
        "date_query": "SELECT MIN(matched_at), MAX(matched_at) FROM unified_match_log",
        "freshness_notes": "Cross-reference and match confidence logs",
    },
    {
        "source_name": "employer_comparables",
        "display_name": "Employer Comparables",
        "group_id": "master_matching",
        "tables": ["employer_comparables", "mv_employer_features"],
        "record_count_note": "~270,000 comparable pairs",
        "description": "Nearest-neighbor comparable employers for benchmarking.",
        "count_query": "SELECT COUNT(*) FROM employer_comparables",
        "date_query": None,
        "freshness_notes": "Employer similarity/comparables",
    },
    {
        "source_name": "organizing_scorecard",
        "display_name": "Organizing Scorecard",
        "group_id": "scoring_pipeline",
        "tables": ["mv_organizing_scorecard"],
        "record_count_note": "~212,000 OSHA establishments scored",
        "description": "Worksite-level organizing potential scores.",
        "count_query": "SELECT COUNT(*) FROM mv_organizing_scorecard",
        "date_query": None,
        "freshness_notes": "Materialized organizing scorecard",
    },
    {
        "source_name": "unified_scorecard",
        "display_name": "Unified Scorecard",
        "group_id": "scoring_pipeline",
        "tables": ["mv_unified_scorecard"],
        "record_count_note": "~146,863 F-7 employers scored",
        "description": "Main multi-factor scorecard for union employers.",
        "count_query": "SELECT COUNT(*) FROM mv_unified_scorecard",
        "date_query": None,
        "freshness_notes": "Materialized unified employer scorecard",
    },
    {
        "source_name": "target_scorecard",
        "display_name": "Target Scorecard",
        "group_id": "scoring_pipeline",
        "tables": ["mv_target_scorecard"],
        "record_count_note": "~4.4M non-union employers ranked",
        "description": "Signal-based ranking of non-union organizing targets.",
        "count_query": "SELECT COUNT(*) FROM mv_target_scorecard",
        "date_query": None,
        "freshness_notes": "Materialized non-union target scorecard",
    },
    {
        "source_name": "search_index",
        "display_name": "Employer Search Index",
        "group_id": "scoring_pipeline",
        "tables": ["mv_employer_search"],
        "record_count_note": "~107,000 searchable employers",
        "description": "Search-optimized employer index for API/frontend.",
        "count_query": "SELECT COUNT(*) FROM mv_employer_search",
        "date_query": None,
        "freshness_notes": "Materialized employer search index",
    },
    {
        "source_name": "research_agent",
        "display_name": "Research Agent Output",
        "group_id": "research_cba",
        "tables": ["research_runs", "research_facts", "research_score_enhancements"],
        "record_count_note": "AI research sessions with extracted facts",
        "description": "AI-generated dossiers and scored research enhancements.",
        "count_query": "SELECT (SELECT COUNT(*) FROM research_runs) + (SELECT COUNT(*) FROM research_facts) + (SELECT COUNT(*) FROM research_score_enhancements)",
        "date_query": "SELECT MIN(started_at), MAX(started_at) FROM research_runs",
        "freshness_notes": "AI research run outputs and fact extraction",
    },
    {
        "source_name": "cba_documents",
        "display_name": "CBA Documents and Provisions",
        "group_id": "research_cba",
        "tables": ["cba_documents", "cba_provisions", "cba_categories"],
        "record_count_note": "Contract texts plus 14 provision categories",
        "description": "Collective bargaining agreement texts and extracted clauses.",
        "count_query": "SELECT (SELECT COUNT(*) FROM cba_documents) + (SELECT COUNT(*) FROM cba_provisions) + (SELECT COUNT(*) FROM cba_categories)",
        "date_query": None,
        "freshness_notes": "CBA corpus and provision extraction",
    },
    {
        "source_name": "public_sector_unions",
        "display_name": "Public Sector Union Data",
        "group_id": "specialized_regional",
        "tables": ["ps_parent_unions", "ps_union_locals", "ps_employers", "ps_bargaining_units"],
        "record_count_note": "24 parent unions, 1,520 locals, 7,987 employers, 438 units",
        "description": "Public-sector union structures and bargaining units.",
        "count_query": "SELECT (SELECT COUNT(*) FROM ps_parent_unions) + (SELECT COUNT(*) FROM ps_union_locals) + (SELECT COUNT(*) FROM ps_employers) + (SELECT COUNT(*) FROM ps_bargaining_units)",
        "date_query": None,
        "freshness_notes": "Public-sector union and employer datasets",
    },
    {
        "source_name": "nyc_labor_data",
        "display_name": "NYC Labor Data",
        "group_id": "specialized_regional",
        "tables": ["nyc_wage_theft_cases", "nyc_ulp_cases", "nyc_debarment_list", "nyc_osha_violations"],
        "record_count_note": "~8,600 NYC violation records",
        "description": "NYC-specific wage theft, ULP, debarment, and OSHA data.",
        "count_query": "SELECT (SELECT COUNT(*) FROM nyc_wage_theft_cases) + (SELECT COUNT(*) FROM nyc_ulp_cases) + (SELECT COUNT(*) FROM nyc_debarment_list) + (SELECT COUNT(*) FROM nyc_osha_violations)",
        "date_query": None,
        "freshness_notes": "NYC enforcement and contractor risk datasets",
    },
    {
        "source_name": "web_scraped_union_data",
        "display_name": "Web-Scraped Union Data",
        "group_id": "specialized_regional",
        "tables": ["web_union_profiles", "web_union_employers", "web_union_news"],
        "record_count_note": "~800 records",
        "description": "Union website intelligence for qualitative context.",
        "count_query": "SELECT (SELECT COUNT(*) FROM web_union_profiles) + (SELECT COUNT(*) FROM web_union_employers) + (SELECT COUNT(*) FROM web_union_news)",
        "date_query": None,
        "freshness_notes": "Scraped union profiles, employers, and news",
    },
]

